[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "elva"
description = "A suite of realtime collaboration apps based on CRDTs."
readme = "README.md"
requires-python = ">=3.8"
keywords = [
  "real time",
  "real-time",
  "realtime",
  "collaboration",
  "sync",
  "crdt",
  "y-crdt",
  "yjs",
  "yrs",
  "suite"
]
# TODO decide about displayed contact information
#authors = [
#  { name = "<name>", email = "<email>" }
#]
#maintainers = [
#  { name = "<name>", email = "<email>" }
#]
# TODO decide on a license
# license = { file = "LICENSE" }
classifiers = [
  "Programming Language :: Python :: 3"
]
dependencies = [
  "websockets",
  "pycrdt>=0.8.3",
  "pycrdt_websockets>=0.12.6",
  "anyio",
  "textual"
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
  "setuptools-scm",
  "tox",
  "twine",
  "mkdocs",
  "mkdocstrings"
]

# TODO complete url list
#[project.urls]
#Homepage = "https://url.to/homepage"
#Issues = "https://url.to/issues"
#Documentation = "https://url.to/docs"
#Repository = "https://url.to/repo"
#"Bug Tracker" = "https://url.to/bug-tracker"
#Changelog = "https://url.to/changelog"

[tool.setuptools]
packages = ["elva"]

[tool.setuptools_scm]
version_file = "elva/_version.py"
